### ISSUE TITLE
what is fb_loss???

### ISSUE THREAD

**Issue by 18242360613** [OniroAI/Universal-segmentation-baseline-Kaggle-Airbus-Ship-Detection#2]
I am a newcomer in the field of image segmentation. I saw fb_loss in your code. I don't understand this function very well. Can you give me some information about this function?

**Comment by voeykovroman** [comment]
Fb_loss is calculated as 1-Fb_score, where Fb_score is a special case of F1 score. You can read more about it here https://en.wikipedia.org/wiki/F1_score. Briefly, given the segmentation ground truth mask and the mask predicted by a network it is a sum of their pairwise pixel products times 2 divided by pairwise pixel sums. And this sum is divided by the number of pixels in 1 mask.

**Comment by 18242360613** [comment]
Thank you for your reply, I understand this. However, what is prob_loss used to measure? Why do labels only retain one item? I don't understand the meaning of the code below.

Prob_trg = target[:, 0, : , :].unsqueeze(1).view(target.size(0), -1).sum(dim=1) > 0

**Comment by voeykovroman** [comment]
The basic idea of this part of the loss is to make target which is non-zero when there are ships on the image and 0 otherwise. It is constructed by summing along the segmentation mask channel (0 channel in the target tensor) and by thresholding it. It is aimed to help a model to learn that it should predict something non-zero even when segmentation mask of the ship is really small.

**Comment by voeykovroman** [comment]
Also if you are interested in image segmentation models you can check our new implementation of MobileNetV3 for instance segmentation supplied with training process notebooks to train it for your own purposes on any appropriate data. 
https://github.com/OniroAI/Instance-segmentation-with-MobileNetV3
